openapi: 3.0.0

info:
  title: m-server # Note. title is your API name
  description: simple testing swagger
  version: 0.0.1 # Note. an arbitrary string that specifies the version of your own API

servers: # Note. API server and base URL
  - url: http://localhost:3000
    description: local server

security: # apply 1 only aothorization globally
  - ApiKeyAuth: []


paths:
  /user:
    get:
      tags:
        - user
      summary: return user info
      responses:
        200:
          $ref: '#/components/responses/ResGetUser'
          
    post:
      tags:
        - user
      summary: Creates a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User" # <-------
      responses:
        200:
          $ref: '#/components/responses/ResErrorCode'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: token

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 10
          example: 10
        name:
          type: string
          pattern: '^[A-Za-z0-9-_]+$'
          example: Arthur-Dent
      required:
        - id
        - name
    ErrorCode:
      properties:
        errcode:
          type: integer
          format: int32
        errmsg:
          type: string
      required:
        - errcode
          
  responses:
    ResErrorCode:
      description: errcode - 0 if successful.
                   otherwise means error happen.
      content:
        application/json:          
          schema:
            $ref: '#/components/schemas/ErrorCode'
    ResGetUser:
      description: get user profile
      content:
        application/json:          
          schema:
            allOf:
              - $ref: '#/components/schemas/ErrorCode'
              - type: object
                properties:
                  data: # insert `User` to `ErrorCode` struct as a key-value pair
                    $ref: "#/components/schemas/User"


            
