/*
 * m-server
 *
 * simple testing swagger
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {

	Id int64 `json:"id"`

	Name string `json:"name"`
}
