openapi: 3.0.0
info:
  title: m-server
  description: simple testing swagger
  version: 0.0.1
servers:
- url: http://localhost:3000
  description: local server
security:
- ApiKeyAuth: []
paths:
  /user:
    get:
      tags:
      - user
      summary: return user info
      responses:
        "200":
          description: errcode - 0 if successful. otherwise means error happen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
    post:
      tags:
      - user
      summary: Creates a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: errcode - 0 if successful. otherwise means error happen.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCode'
components:
  schemas:
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          minimum: 100
          type: integer
          format: int64
          example: 4
        name:
          type: string
          example: Arthur Dent
    ErrorCode:
      properties:
        errcode:
          type: integer
          format: int32
      example:
        errcode: 0
  responses:
    ResErrorCode:
      description: errcode - 0 if successful. otherwise means error happen.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorCode'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: token
      in: header
