// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6yTTW/UPhDGv4o1//8xTdwXcfCtFIQQFwTiVO3BJLOJy/qlM+OWVZXvjuwsu0QLt97s",
	"2PObZx4/eYE++hQDBmEwL0DIKQbGuvmC/J4o0l0csOz7GASDlKVNaed6Ky6G7oFjKN+4n9DbsvqfcAsG",
	"/utO8G455e5EnOe5gQG5J5cKCAwgUR8HVBdKK7dVnPsembd516ooE9KzY1QebWCFhaMmmxKGFgrq0KEI",
	"WMlOFBOSuGWoQ4uy3EbyVsCAC3J9BQ3IPuGyxRFpEfiNkc4pbqisn9anHYK5aVawNzfQgHfB+ezBXGp9",
	"jm4gWI8rCNySTJnUu+LxsYKFXBjrgISP2REOYO6LgANic7wavz9gL4sX2Gdysv9aPFkk3yb3Cfe3WaY6",
	"QLF7Qjsg/QYZkPgDw6m1rRWLDS5sY6lbvxe7Il0JsrgwKn6241iB4qSO5C8Y6al+ekLipUq3ur0sFsSE",
	"wSYHBq5b3WpoIFmZqtouH3wfsQaumF/j9nEAAx9Q6rs068Beaf2v+B3vdatUV6+y95b2YIBQMgVVWqs6",
	"cANiRy5+VzmbuYEU+S+CPkc+KXrMyPI2DvtX+2kqel5nQCjj/MoG3BFaQVZWBXyuPrTnHvyZLzD362Td",
	"b+ZNOS6PzvV0nZhd7O1OHUORaVdyKJJM19WzKbKYa601zJv5VwAAAP//DlRcQp8EAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
