// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for LoginInChannelId.
const (
	N0 LoginInChannelId = 0
	N1 LoginInChannelId = 1
	N2 LoginInChannelId = 2
)

// Defines values for LoginInPlatform.
const (
	Android LoginInPlatform = "android"
	Iphone  LoginInPlatform = "iphone"
)

// ErrorCode defines model for ErrorCode.
type ErrorCode struct {
	Errcode int32   `json:"errcode"`
	Errmsg  *string `json:"errmsg,omitempty"`
}

// LoginIn defines model for LoginIn.
type LoginIn struct {
	// ChannelId 0 for dev, 1 for wchat, 2 for qq
	ChannelId *LoginInChannelId `json:"channelId,omitempty"`
	OpenId    string            `json:"openId"`
	Platform  LoginInPlatform   `json:"platform"`
}

// LoginInChannelId 0 for dev, 1 for wchat, 2 for qq
type LoginInChannelId int

// LoginInPlatform defines model for LoginIn.Platform.
type LoginInPlatform string

// LoginOut defines model for LoginOut.
type LoginOut struct {
	Token string `json:"token"`
}

// UserIn defines model for UserIn.
type UserIn struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// UserOut defines model for UserOut.
type UserOut = UserIn

// ResError defines model for ResError.
type ResError = ErrorCode

// ResLogin defines model for ResLogin.
type ResLogin struct {
	Data    *LoginOut `json:"data,omitempty"`
	Errcode int32     `json:"errcode"`
	Errmsg  *string   `json:"errmsg,omitempty"`
}

// ResUserGet defines model for ResUserGet.
type ResUserGet struct {
	Data    *UserOut `json:"data,omitempty"`
	Errcode int32    `json:"errcode"`
	Errmsg  *string  `json:"errmsg,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginIn

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = UserIn
