// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// ErrorCode defines model for ErrorCode.
type ErrorCode struct {
	Errcode int32  `json:"errcode"`
	Errmsg  string `json:"errmsg"`
}

// User defines model for User.
type User struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// ResErrorCode defines model for ResErrorCode.
type ResErrorCode = ErrorCode

// PostUserJSONRequestBody defines body for PostUser for application/json ContentType.
type PostUserJSONRequestBody = User
