/*
 * m-server
 *
 * simple testing swagger
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorCode struct {

	Errcode int32 `json:"errcode,omitempty"`
}
